### PR TITLE
Fix #98: Exceptionhandlers are not fully supported 

### LINKED ISSUE #98: Exceptionhandlers are not fully supported
This unit

```Delphi
unit tryexcept;

interface

implementation

procedure DoStuff;
begin
  try
   DoSomething;
  except
    Log('DoSomething failed');
  end; 

  try
    DoSomethingElse
  except
    on E: Exception do
    begin
      LogError(E);
    end;
  end;
  
  try
    DoCrazyStuff;
  except
  
    on E: EFileNotFound do
    begin
      LogError('File not found!', E);
    end;  
  
    on E: Exception do
    begin
      LogError(E);
    end
    else
      LogError('Unknown error');
  end;              
end;

end.
```

is represented by this AST

```xml
<?xml version="1.0"?>
<UNIT line="1" col="1" name="tryexcept">
  <INTERFACE line="3" col="1"/>
  <IMPLEMENTATION line="5" col="1">
    <METHOD line="7" col="1" kind="procedure" name="DoStuff">
      <STATEMENTS begin_line="8" begin_col="1" end_line="40" end_col="4">
        <TRY line="9" col="3">
          <STATEMENTS begin_line="10" begin_col="4" end_line="11" end_col="3">
            <CALL line="10" col="4">
              <IDENTIFIER line="10" col="4" name="DoSomething"/>
            </CALL>
          </STATEMENTS>
          <EXCEPT line="12" col="5">
            <STATEMENTS begin_line="12" begin_col="5" end_line="13" end_col="3">
              <CALL line="12" col="5">
                <CALL line="12" col="5">
                  <IDENTIFIER line="12" col="5" name="Log"/>
                  <EXPRESSIONS line="12" col="9">
                    <EXPRESSION line="12" col="9">
                      <LITERAL line="12" col="29" value="DoSomething failed" type="string"/>
                    </EXPRESSION>
                  </EXPRESSIONS>
                </CALL>
              </CALL>
            </STATEMENTS>
          </EXCEPT>
        </TRY>
        <TRY line="15" col="3">
          <STATEMENTS begin_line="16" begin_col="5" end_line="17" end_col="3">
            <CALL line="16" col="5">
              <IDENTIFIER line="16" col="5" name="DoSomethingElse"/>
            </CALL>
          </STATEMENTS>
          <EXCEPT line="18" col="5">
            <EXCEPTIONHANDLER line="18" col="5">
              <IDENTIFIER line="18" col="11" name="Exception"/>
              <STATEMENTS begin_line="19" begin_col="5" end_line="21" end_col="8">
                <CALL line="20" col="7">
                  <CALL line="20" col="7">
                    <IDENTIFIER line="20" col="7" name="LogError"/>
                    <EXPRESSIONS line="20" col="16">
                      <EXPRESSION line="20" col="16">
                        <IDENTIFIER line="20" col="16" name="E"/>
                      </EXPRESSION>
                    </EXPRESSIONS>
                  </CALL>
                </CALL>
              </STATEMENTS>
            </EXCEPTIONHANDLER>
          </EXCEPT>
        </TRY>
        <TRY line="24" col="3">
          <STATEMENTS begin_line="25" begin_col="5" end_line="26" end_col="3">
            <CALL line="25" col="5">
              <IDENTIFIER line="25" col="5" name="DoCrazyStuff"/>
            </CALL>
          </STATEMENTS>
          <EXCEPT line="28" col="5">
            <EXCEPTIONHANDLER line="28" col="5">
              <IDENTIFIER line="28" col="11" name="EFileNotFound"/>
              <STATEMENTS begin_line="29" begin_col="5" end_line="31" end_col="8">
                <CALL line="30" col="7">
                  <CALL line="30" col="7">
                    <IDENTIFIER line="30" col="7" name="LogError"/>
                    <EXPRESSIONS line="30" col="16">
                      <EXPRESSION line="30" col="16">
                        <LITERAL line="30" col="33" value="File not found!" type="string"/>
                      </EXPRESSION>
                      <EXPRESSION line="30" col="35">
                        <IDENTIFIER line="30" col="35" name="E"/>
                      </EXPRESSION>
                    </EXPRESSIONS>
                  </CALL>
                </CALL>
              </STATEMENTS>
            </EXCEPTIONHANDLER>
            <EXCEPTIONHANDLER line="33" col="5">
              <IDENTIFIER line="33" col="11" name="Exception"/>
              <STATEMENTS begin_line="34" begin_col="5" end_line="37" end_col="5">
                <CALL line="35" col="7">
                  <CALL line="35" col="7">
                    <IDENTIFIER line="35" col="7" name="LogError"/>
                    <EXPRESSIONS line="35" col="16">
                      <EXPRESSION line="35" col="16">
                        <IDENTIFIER line="35" col="16" name="E"/>
                      </EXPRESSION>
                    </EXPRESSIONS>
                  </CALL>
                </CALL>
              </STATEMENTS>
            </EXCEPTIONHANDLER>
            <STATEMENTS begin_line="38" begin_col="7" end_line="39" end_col="3">
              <CALL line="38" col="7">
                <CALL line="38" col="7">
                  <IDENTIFIER line="38" col="7" name="LogError"/>
                  <EXPRESSIONS line="38" col="16">
                    <EXPRESSION line="38" col="16">
                      <LITERAL line="38" col="31" value="Unknown error" type="string"/>
                    </EXPRESSION>
                  </EXPRESSIONS>
                </CALL>
              </CALL>
            </STATEMENTS>
          </EXCEPT>
        </TRY>
      </STATEMENTS>
    </METHOD>
  </IMPLEMENTATION>
</UNIT>
```
 - All these `E` declarations in `on E: ExceptionType do` are completely ignored 
 - `ExceptionType` is represented as identifier
 - The `else` keyword is missing in AST

### PR DESCRIPTION
**Pull request by Wosi**
Exceptionhandlers can now contain a node of ntVariable for `on E: Exception do` or a node of ntType for `on Exception do`.
The else branch in `except`block is now also represented in AST.

### CODE REVIEW

File: Source/DelphiAST.pas [hunk 1]
```diff
@@ -924,6 +936,18 @@ procedure TPasSyntaxTreeBuilder.ExceptionHandler;
   end;
 end;
 
+procedure TPasSyntaxTreeBuilder.ExceptionVariable;
+begin
+  FStack.Push(ntVariable);
+  FStack.Push(ntName).SetAttribute(sVALUE, Lexer.Token);
```
Comment (RomanYankovsky) [inline Source/DelphiAST.pas]: You can replace this push/pop with FStack.AddChild, it will look more clear. Could you please update the code?

Comment (Wosi) [inline Source/DelphiAST.pas]: No problem. Done.

**Comment by RomanYankovsky** [comment]
Thanks!
